### ISSUE TITLE
custom stylgan3 model

### ISSUE THREAD

**Issue by nicolai256** [NVlabs/eg3d#13]
i'm training a custom stylegan3 model, will it work fine in eg3d or will it need to retrain? 
thanks

**Comment by woctezuma** [comment]
The code will most likely be for StyleGAN2.

> By decoupling feature generation and neural rendering, our framework is able to leverage state-of-the-art 2D CNN generators, such as StyleGAN2, and inherit their efficiency and expressiveness.

> Our method inherits the qualities of the StyleGAN2 backbone, including a well-behaved latent space.

> In using StyleGAN2 as the backbone of our representation, we inherit the qualities of the backbone, including a well-behaved latent space. 

Reference: https://matthew-a-chan.github.io/EG3D/

**Comment by ericryanchan** [comment]
We train the entire network from scratch, i.e. while the StyleGAN network is an integral part of the model, we don't start from any pretrained 2D StyleGAN. However, we build off of the StyleGAN3 repo and swapping in different architectures for the backbone should be straightforward! I expect that you'll be able to carry over tweaks and modifications into EG3D, though you'll need to retrain.
