### ISSUE TITLE
Flickering in generated videos

### ISSUE THREAD

**Issue by oneThousand1000** [NVlabs/eg3d#17]
Good work!
I try to run gen_videos.py to generate videos, it seems like in the results the interpolation is not smooth with some flickering. But the flickering is not apparent in the demo videos on your [project page](https://nvlabs.github.io/eg3d/). 

Could you tell me why the results are not smooth?

https://user-images.githubusercontent.com/32099648/172812581-34d5f125-987c-4731-98e5-1387a89c8891.mp4

**Comment by oneThousand1000** [comment]
> Hello! You can pass the `--sample_mult` argument to increase the number of depth samples at inference, which reduces flicker. Try using `--sample_mult=2`.

Thank you for your guidance!

**Comment by luminohope** [comment]
I updated the video script to use 2x depth sample by default now
