### ISSUE TITLE
Issues with GLFW

### ISSUE THREAD

**Issue by RaphaelJDDS** [NVlabs/eg3d#19]
Whenever I try to use the visualizer.py program, I stumble upon these errors:
```
/root/miniconda3/envs/eg3d/lib/python3.9/site-packages/glfw/__init__.py:834: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
/root/miniconda3/envs/eg3d/lib/python3.9/site-packages/glfw/__init__.py:834: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)
python3: /builds/florianrhiem/pyGLFW/glfw-3.3.4/src/input.c:832: glfwSetKeyCallback: Assertion `window != ((void *)0)' failed.
Aborted (core dumped)
```
I installed all the requirements specified in the environment.yml file, I also tried using some other versions of GLFW, but it didn't work (test done for redundancy). I have no experience with GLFW, could someone help me with this?

**Comment by luminohope** [comment]
The visualizer framework borrows the structures from the StyleGAN3. https://github.com/NVlabs/stylegan3/issues?q=glfw
So first, I would suggest you check their issues to see if there is anything relevant.

**Comment by RaphaelJDDS** [comment]
Thank you so much, there I found a similar issue, and then, as recommended, I tried to run it on Windows (cmd.exe), it ran and worked as expected.

**Comment by RaphaelJDDS** [comment]
Well, I basically ran Miniconda on Windows command prompt (cmd.exe) and followed the same steps as in the main instructions, and it _surprisingly_ worked as expected, although the images looked awful initially (but this has absolutely nothing to deal with this issue).
