### ISSUE TITLE
Few questions about the paper

### ISSUE THREAD

**Issue by PeterL1n** [NVlabs/eg3d#2]
Awesome work. I have a few questions about the paper.

1. Was using a single StyleGan as backbone instead of 3 separate ligher-weight StyleGan to generate the triplane deliberate. My thought was that the triplane is mostly not pixel aligned and it could be wasteful for the convolution.

2. The paper says MLP uses softmax activation. Do you mean softmax for the hidden layer or the output layer? What's the reason for using softmax?

3. Has there been any exploration on using it with StyleGan3-R?

4. When will the code and weights be released.

**Comment by YutongZheng** [comment]
Same questions here. 

I have some thoughts about the Softmax activation though. I think it should be applied along depth of the hidden layer. Such that only a limited number of sample points along each ray are "activated". Anyway, that is only my intuition. We should still wait for the official reply...

**Comment by shoutOutYangJie** [comment]
> Awesome work. I have a few questions about the paper.
> 
> 1. Was using a single StyleGan as backbone instead of 3 separate ligher-weight StyleGan to generate the triplane deliberate. My thought was that the triplane is mostly not pixel aligned and it could be wasteful for the convolution.
> 2. The paper says MLP uses softmax activation. Do you mean softmax for the hidden layer or the output layer? What's the reason for using softmax?
> 3. Has there been any exploration on using it with StyleGan3-R?
> 4. When will the code and weights be released.

I also think the tirplane is generated by three stylegan2 backbone. Because I have tried to implement it by one stylegan2 backbone, and it is a shit.
![image](https://user-images.githubusercontent.com/46734514/150714105-15fc31ce-1218-4a6f-80a8-95381def44d9.png)
