### ISSUE TITLE
about face alignment

### ISSUE THREAD

**Issue by h1a2l1o5** [NVlabs/eg3d#25]
HI! thanks for sharing awesome works!

I created projection module, 
project this image
![test](https://user-images.githubusercontent.com/71425068/173574172-117045d0-ad13-4c3c-8784-e407494f0c13.png)
to project this video

but when alignment is a little bit wrong, then the result is terrible.
![yeah2](https://user-images.githubusercontent.com/71425068/173573814-b2ee1a15-fcf8-440d-adbe-86b3774ec97e.png)
![test_sr_only](https://user-images.githubusercontent.com/71425068/173573833-26c03de7-a802-445f-8de4-c56b071ae535.png)
I think it is about alingment problem or extrinsic/intrinsic extraction code is the problem.

I have two questions

1. did you align face again after extract extrinsic parameter to get a correct head position?
2. how do you extract extrinsic/intrinsic parameter from this [repo](https://github.com/sicxu/Deep3DFaceRecon_pytorch), i cannot found anything from it.

Thanks.

**Comment by MartinMao1101** [comment]
> HI! thanks for sharing awesome works!
> 
> I created projection module, project this image ![test](https://user-images.githubusercontent.com/71425068/173574172-117045d0-ad13-4c3c-8784-e407494f0c13.png) to project this video
> 
> but when alignment is a little bit wrong, then the result is terrible. ![yeah2](https://user-images.githubusercontent.com/71425068/173573814-b2ee1a15-fcf8-440d-adbe-86b3774ec97e.png) ![test_sr_only](https://user-images.githubusercontent.com/71425068/173573833-26c03de7-a802-445f-8de4-c56b071ae535.png) I think it is about alingment problem or extrinsic/intrinsic extraction code is the problem.
> 
> I have two questions
> 
> 1. did you align face again after extract extrinsic parameter to get a correct head position?
> 2. how do you extract extrinsic/intrinsic parameter from this [repo](https://github.com/sicxu/Deep3DFaceRecon_pytorch), i cannot found anything from it.
> 
> Thanks.

Hello @h1a2l1o5 
i am trying to train this EG3D further with my own dataset without GT data. I am now facing the same problem as you mentioned here. Have you figured out how to extract the extrinsic and intrinsic by using the Deep3dFaceRecon? Or do you know any other method to get the extrinsic and intrinsic?
Thanks a lot in advance!
