### ISSUE TITLE
How to pass an input?

### ISSUE THREAD

**Issue by oTree-org** [NVlabs/eg3d#29]
Hi, I downloaded ffhqrebalanced512-128.pkl then ran the command suggested in the readme:

```
python gen_videos.py --outdir=out --trunc=0.7 --seeds=0-3 --grid=2x2 \
    --network=ffhqrebalanced512-128.pkl
```

The output is a black video with some red lines around the edges that flicker a bit.

I'm wondering what the expected output is? Shouldn't I be passing some input image to be transformed? There is the .pkl file, but I thought that is just a model trained on hundreds of input faces. So shouldn't it be input + model => output?

**Comment by luminohope** [comment]
Hi there, this is an unconditional model so the output is generated by the seeds. I suspect something is wrong in the installation etc.
