### ISSUE TITLE
Issue with runme.py -- permission denied

### ISSUE THREAD

**Issue by datasciencegrimmer** [NVlabs/eg3d#31]
Hello,

I'm having issues downloading the FFHQ "in-the-wild" images with **runme.py**. Seems like the permission is denied for some content:

![image](https://user-images.githubusercontent.com/65238331/175572073-80aa0d69-9057-4cec-91d3-5a292ae52fc8.png)

Anyone knows how to deal with that? Thank you in advance!

**Comment by HuaZheLei** [comment]
The same.

**Comment by datasciencegrimmer** [comment]
Haven't really fixed the issue, but found a workaround: It seems like the images can only be downloaded batch-wise from google drive(?).  After waiting ~20-30 min, it is possible to continue downloading. Therefore, I am running "runme.py" script in a  scheduled crontab that initializes the download every 20-30 minutes automatically...
