### ISSUE TITLE
Noisy geometry

### ISSUE THREAD

**Issue by cantonioupao** [NVlabs/eg3d#33]
Hello, 

I load the .ply file as a mesh in a mesh viewer and I get some very noisy geometry of the face. In your paper , the geometry/shape results are not so noisy/spiky! The above geometry has a voxel resolution of 512 with sampling multiplier of 4.
![noisy_mesh](https://user-images.githubusercontent.com/47451846/176771111-24db1639-33cd-49a7-8c9b-2bad67166d1c.png)

Any suggestions on how to avoid this?

**Comment by zhangqianhui** [comment]
hi, which tools you used to visualize?

**Comment by cantonioupao** [comment]
I am currently using MeshLab

**Comment by zhangqianhui** [comment]
Thanks, how to render mesh to image, do you use another tool, such as
blender?
