### ISSUE TITLE
Type of Cameras for Pytorch3D rendering

### ISSUE THREAD

**Issue by cantonioupao** [NVlabs/eg3d#37]
Hello!

I am saving the camera parameters during the synthesis of the images and I reconstruct the meshes using the '.ply'data and Pytorch3D. However I a cannot get a good rendering because of issues with the camera pose. The exact problem is that I am not sure what type of camera you are using for your rendering. Should I use a Perspective or Orthographic Camera?

**Comment by luminohope** [comment]
Hello,
 
We use a perspective camera and the camera coordinate convention described in here: https://github.com/NVlabs/eg3d/blob/main/docs/training_guide.md
