### ISSUE TITLE
Ask for ffhq-64.pkl

### ISSUE THREAD

**Issue by oneThousand1000** [NVlabs/eg3d#41]
Hi! I noticed that you finetuned `ffhq512-128.pkl` and `ffhqrebalanced512-64.pkl` based on the `ffhq-64.pkl`, which is not included on the [NGC Catalog](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/research/models/eg3d). 

Maybe the `ffhq-64.pkl` is a good starting point for finetuning? 

Could you please upload `ffhq-64.pkl`?

Thanks!

**Comment by luminohope** [comment]
Hi, that does not mean that you need to use ffhq-64.pkl for fine-tuning. 
The checkpoints we released (ffhqrebalanced512-128.pkl, ffhqrebalanced512-64.pkl, ffhq512-128.pkl etc) are a even better starting point and I suggest using those.

**Comment by oneThousand1000** [comment]
> Hi, that does not mean that you need to use ffhq-64.pkl for fine-tuning.
> The checkpoints we released (ffhqrebalanced512-128.pkl, ffhqrebalanced512-64.pkl, ffhq512-128.pkl etc) are a even better starting point and I suggest using those.

Thanks for your reply!

**Comment by oneThousand1000** [comment]
> Hi, that does not mean that you need to use ffhq-64.pkl for fine-tuning. The checkpoints we released (ffhqrebalanced512-128.pkl, ffhqrebalanced512-64.pkl, ffhq512-128.pkl etc) are a even better starting point and I suggest using those.

Hi luminohope, I want to finetune your model at the low neural rendering resolutions of 64 (faster, as you mentioned in training_guide). 

I tried ffhq512-128.pkl, but it is trained at `neural_rendering_resolution=128` and generates blurry results if I simply set `neural_rendering_resolution=64`. `ffhqrebalanced512-64.pkl` does not work for me because its data distribution has changed a lot.

Could you please upload the `ffhq-64.pkl` (or `ffhq512-64.pkl`)?  Or could you tell me how to finetune `ffhq512-128.pkl` at neural rendering resolution of 64?
