### ISSUE TITLE
Quesion about the camera extrinsic matrix

### ISSUE THREAD

**Issue by zhanglonghao1992** [NVlabs/eg3d#44]
Hi～
I found that the camera extrinsic matrix in `dataset.json` is a little strange. 
Since in [the world coordinate system of eg3d](https://github.com/NVlabs/eg3d/blob/main/docs/training_guide.md), the y-axis points out of the screen and the z-axis points up, why is trans_y close to 0 and trans_z close to 2.6 for most faces? In my understanding, (trans_x, trans_y, trans_z) is the position of the camera in the world coordinate system. In this way, the camera is above the head in most cases.

**Comment by yanre-hyd** [comment]
> Hi～ 我发现里面的相机外参矩阵`dataset.json`有点奇怪。 既然在[eg3d的世界坐标系](https://github.com/NVlabs/eg3d/blob/main/docs/training_guide.md)中，y轴指向屏幕外，z轴指向上方，为什么对于大多数人脸来说，trans_y接近0，trans_z接近2.6？在我的理解中，(trans_x, trans_y, trans_z) 是相机在世界坐标系中的位置。这样，大多数情况下摄像头都在头顶上方。

How did you obtain the matrix information in your dataset.json file?thank you！
