### ISSUE TITLE
"environment.yml" file is missing

### ISSUE THREAD

**Issue by biesseck** [NVlabs/eg3d#57]
Congrats for your great work at CVPR 2022!

I'm trying to run your code, but couldn't find the "environment.yml" file at [https://github.com/NVlabs/eg3d/blob/main/environment.yml](https://github.com/NVlabs/eg3d/blob/main/environment.yml), as specified on the README.md.

Would it be possible to make it available?
Thank you so much!

Bernardo Biesseck

**Comment by WuHaoZhan2000** [comment]
> Congrats for your great work at CVPR 2022!
> 
> I'm trying to run your code, but couldn't find the "environment.yml" file at https://github.com/NVlabs/eg3d/blob/main/environment.yml, as specified on the README.md.
> 
> Would it be possible to make it available? Thank you so much!
> 
> Bernardo Biesseck

The path of this file is: 
eg3d/eg3d/environment.yml

**Comment by WuHaoZhan2000** [comment]
> Congrats for your great work at CVPR 2022!
> 
> I'm trying to run your code, but couldn't find the "environment.yml" file at https://github.com/NVlabs/eg3d/blob/main/environment.yml, as specified on the README.md.
> 
> Would it be possible to make it available? Thank you so much!
> 
> Bernardo Biesseck

The path of this file is:
https://github.com/NVlabs/eg3d/blob/main/eg3d/environment.yml

**Comment by luminohope** [comment]
Sorry about the wrong path and thanks for reporting. Updated.
