### ISSUE TITLE
How to create 3d model from image, thanks

### ISSUE THREAD

**Issue by testouya** [NVlabs/eg3d#60]
hello, 
I want to input a 2d face picture, and output a 3d model(such as obj format),
but I cant find the way in the gen_samples.py and gen_video.py.
Does this version support this funtion now?
If support, which command should I input, thanks.

**Comment by luminohope** [comment]
Hi, there is an [unofficial inversion code](https://github.com/oneThousand1000/EG3D-projector) that perhaps you could try.

**Comment by testouya** [comment]
thanks！

**Comment by kashishnaqvi101** [comment]
> hello, I want to input a 2d face picture, and output a 3d model(such as obj format), but I cant find the way in the gen_samples.py and gen_video.py. Does this version support this funtion now? If support, which command should I input, thanks.

Hi, were you able to get .obj from .mrc?
