### ISSUE TITLE
How to generate a video for mesh

### ISSUE THREAD

**Issue by Twizwei** [NVlabs/eg3d#66]
Thanks for sharing the code for this great work!

I have a question about how we can generate a video for mesh from multiple views, like Video 2 [here](https://nvlabs.github.io/eg3d/)? It could be useful if you can provide some tutorials or codes! Thanks!

**Comment by matthew-a-chan** [comment]
Hi, Thanks for the question! I don't think we have any of the actual code anymore, but I'd be happy to describe the pipeline:

- We first extract the densities as `.mrc` files as described in the readme: https://github.com/NVlabs/eg3d#generating-media
- Convert the densities into a levelset mesh `.obj` using ChimeraX: https://github.com/NVlabs/eg3d#generating-media
- Import the mesh into Blender
- Render frames using Blender

For the interpolation videos, we export and extract one mesh per frame.

**Comment by Twizwei** [comment]
Hi @matthew-a-chan, thanks for your answer! I ended up with using pyrender for the video frame by frame, and it works well.

**Comment by luchaoqi** [comment]
> Hi @matthew-a-chan, thanks for your answer! I ended up with using pyrender for the video frame by frame, and it works well.

Hi Yiran @Twizwei , could you share the code to generate video 2 using pyrender or illustrate a bit about the pipeline?
