### ISSUE TITLE
Missing images after preprocessing FFHQ's in-the-wild-images	

### ISSUE THREAD

**Issue by thuanz123** [NVlabs/eg3d#70]
I have download the original in-the-wild-images for preprocessing and have validate that all original 70000 images is not corrupted, however after preprocessing using the instruction in the README, the final crop folder miss 43 images. Is this expected or your code is not correct ?

**Comment by oneThousand1000** [comment]
I think those images can not be detected by mtcnn, so the authors removed them from eg3d training dataset.

**Comment by thuanz123** [comment]
> I think those images can not be detected by mtcnn, so the authors removed them from eg3d training dataset.

So is it OK to train eg3d with these images missing ?

**Comment by oneThousand1000** [comment]
> > I think those images can not be detected by mtcnn, so the authors removed them from eg3d training dataset.
> 
> So is it OK to train eg3d with these images missing ?

Yes, it is ok. In https://github.com/NVlabs/eg3d/issues/30#issuecomment-1184158745 someone got nice results using only ~5k images.

**Comment by thuanz123** [comment]
Thanks a lot. I will close this then
