### ISSUE TITLE
Why is the focal length equal to 2985.29?

### ISSUE THREAD

**Issue by Rodger-Huang** [NVlabs/eg3d#71]
I follow your advice to prepare the training datasets by cropping in-the-wild face images and extracting poses using [Deep3DFaceRecon_pytorch](https://github.com/sicxu/Deep3DFaceRecon_pytorch/tree/6ba3d22f84bf508f0dde002da8fff277196fef21). But I don't understand why the focal length is calculated as:

https://github.com/NVlabs/eg3d/blob/493076071bc400be3289dd6725ef1eef0a552a9d/dataset_preprocessing/ffhq/3dface2idr_mat.py#L53

Why it is divided by 466.285? In [Deep3DFaceRecon_pytorch](https://github.com/sicxu/Deep3DFaceRecon_pytorch/tree/6ba3d22f84bf508f0dde002da8fff277196fef21), the rescale factor is equal to `102`, so I think it should be:
```
focal = 1015*1024/224*(300/102)
```
Is my understanding right?

**Comment by chenerg** [comment]
@Rodger-Huang @luminohope   Hi, I'm confused about the rescale factor, would you mind giving a brief introduction to the rescale factor?

**Comment by belgacemi** [comment]
> @Rodger-Huang @luminohope Hi, I'm confused about the rescale factor, would you mind giving a brief introduction to the rescale factor?

+1

**Comment by pfeducode** [comment]
> > @Rodger-Huang @luminohope嗨，我对重新缩放因子感到困惑，你介意简单介绍一下重新缩放因子吗？
> 
> +1

3D perspective projection
