### ISSUE TITLE
Bad quality in extreme pose face generation

### ISSUE THREAD

**Issue by anjith2006** [NVlabs/eg3d#75]
I am observing that there are artefacts when face is in extreme poses (+-90 degree yaw), Is there a way to avoid this. Or is it the background ? An example is shown here.
![Screenshot 2022-10-20 at 3 23 00 PM](https://user-images.githubusercontent.com/5804284/196960635-d45ca869-6842-4efd-b4b4-d6bb3731aa2f.png)

Thanks!

**Comment by matthew-a-chan** [comment]
Hi,

Thanks for the comment. This is somewhat expected for the FFHQ (and AFHQ) models. Both of these faces datasets contain almost entirely frontal views (in fact, the majority of FFHQ faces fall within ~30 degree deviation from frontal). For that reason, the +-90 degree views you show here are essentially unseen in training.

For your case specifically, It's hard to diagnose the exact problem from just these images but there's a chance that increasing the near plane could help reduce floaters (but may also possibly cut into the person's face, if increased too much).
