### ISSUE TITLE
The triplanes in the volumetric rendering wrong?

### ISSUE THREAD

**Issue by ParthaEth** [NVlabs/eg3d#89]
If you look here - 
https://github.com/NVlabs/eg3d/blob/main/eg3d/training/volumetric_rendering/renderer.py#L35
The planes look to me to be xy, xz, zx. Should have been xy, yz, xz

**Comment by MrTornado24** [comment]
Please refer to this issue: https://github.com/NVlabs/eg3d/issues/67
