### ISSUE TITLE
Why the addition?

### ISSUE THREAD

**Issue by BinglunWang** [NVlabs/eg3d#99]
Hi,

Thank you for your work! I found that the use of tri-plane representation is simply a brilliant method.

I have a quick question. After interpolation, I found: Instead of concatenation, you add three plane features. 

Because the addition will always introduce ambiguity. Example:
10 = 5 + 0 + 5
10 = 7 + 2 + 1
10 = 8 + 1 + 1
10 = 2 + 2 + 6
and so on...
So, I intuitively think that concatenate might be better. May I know why you want to use addition? For example, is there some intuitive explanation?

Any answers would help me a lot. Thank you very much in advance.

**Comment by ericryanchan** [comment]
Hi Binglun, we use addition mainly for simplicity! It's a generally well-accepted and proven way of aggregating a set of features. But other strategies are certainly valid! Concatenation is one option, and the Hadamard product (https://sarafridov.github.io/K-Planes/) is another.
